export const TODOS_FETCH_REQUESTED = 'TODOS_FETCH_REQUESTED';
export const TODOS_FETCH_SUCCEEDED = 'TODOS_FETCH_SUCCEEDED';
export const CREATE_TODO_REQUESTED = 'CREATE_TODO_REQUESTED';
export const UPDATE_TODO_REQUESTED = 'UPDATE_TODO_REQUESTED';
export const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED';
export const CLEAR_TODOS_REQUESTED = 'CLEAR_TODOS_REQUESTED';
export const TOGGLE_ONLY_ACTIVE = 'TOGGLE_ONLY_ACTIVE';
